/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-18 02:08:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import product.model.vo.*;
import member.model.vo.member;

public final class productList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1637105211176L));
    _jspx_dependants.put("/WEB-INF/views/common/imgslide.jsp", Long.valueOf(1636376437037L));
    _jspx_dependants.put("/WEB-INF/views/common/bottontitle.jsp", Long.valueOf(1636376446868L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("product.model.vo");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	ArrayList<Product> pList = (ArrayList)request.getAttribute("pList"); 
	ArrayList<Photo> fList = (ArrayList<Photo>)request.getAttribute("fList");
	PageInfo pi = (PageInfo)request.getAttribute("pi");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("#nav_list{\r\n");
      out.write("	height: 50px;\r\n");
      out.write("}\r\n");
      out.write(".cateNav { \r\n");
      out.write("\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 1200px; \r\n");
      out.write("	height: 50px; \r\n");
      out.write("	margin: auto 350px;; \r\n");
      out.write("	text-align: center; \r\n");
      out.write("	font-size:20px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("} \r\n");
      out.write("#cateNavDiv{\r\n");
      out.write("	background-color: white;\r\n");
      out.write("}\r\n");
      out.write(".cateNav ul { \r\n");
      out.write("	display: table; \r\n");
      out.write("	margin: auto; \r\n");
      out.write("	padding:0; \r\n");
      out.write("} \r\n");
      out.write(".cateNav li {\r\n");
      out.write(" 	width: 130px;\r\n");
      out.write(" 	margin: 40px 10px;\r\n");
      out.write(" 	padding: 0px;\r\n");
      out.write("	float: left; \r\n");
      out.write("	text-align: center; \r\n");
      out.write("	display:inline-block; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cateNav li a{\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write(".cateNav li:hover a{\r\n");
      out.write("	background: rbg(0, 100, 0);\r\n");
      out.write("	border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write(".cateNav::after{\r\n");
      out.write("	 clear:both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".prodContent {\r\n");
      out.write("		margin : 40px auto;\r\n");
      out.write("		width: 1200px;\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write(".proFlex{\r\n");
      out.write("	display:flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	flex-wrap: nowrap;\r\n");
      out.write("}\r\n");
      out.write("	.prodCol{\r\n");
      out.write("		margin: 40px;\r\n");
      out.write("		width : 33%;\r\n");
      out.write("		padding-right : 8px;\r\n");
      out.write("		text-align : center;\r\n");
      out.write("	}\r\n");
      out.write("	.prodCol a{\r\n");
      out.write("		text-decoration: none;\r\n");
      out.write("		color: black;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.prodCol *:hover{\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.nav-item{\r\n");
      out.write("		margin: 30px 0;\r\n");
      out.write("		font-size: 20px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		font-color: black;\r\n");
      out.write("	}\r\n");
      out.write("	.nav-link{\r\n");
      out.write("		color: black;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/*.img-thumb {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		border-style: none;\r\n");
      out.write("		}*/\r\n");
      out.write("	.name-product {\r\n");
      out.write("		margin : 16px 0 4px 0;\r\n");
      out.write("		font-weight : bold;\r\n");
      out.write("	}\r\n");
      out.write("	.price-product {\r\n");
      out.write("		font-size : 20px;\r\n");
      out.write("		font-weight : bold;\r\n");
      out.write("		line-height : 150%;\r\n");
      out.write("		color : red;\r\n");
      out.write("	}\r\n");
      out.write("	.proThumb:hover{\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    ");

    member loginUser = (member)session.getAttribute("loginUser");
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" >\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\">\r\n");
      out.write("<style>\r\n");
      out.write("	\r\n");
      out.write("	*{\r\n");
      out.write("		box-sizing: border-box;\r\n");
      out.write("		margin: 0;\r\n");
      out.write("		padding: 0;\r\n");
      out.write("		font-family: 'poppins', snas-serif;\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	.links{\r\n");
      out.write("		max-width : 1000px;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: space-between;\r\n");
      out.write("		margin-top: 30px;\r\n");
      out.write("	}\r\n");
      out.write("	.leftlinks>a{\r\n");
      out.write("	margin-left: 20px;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	}\r\n");
      out.write("	header a{\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color:#606060;\r\n");
      out.write("	}\r\n");
      out.write("	header a:hover{\r\n");
      out.write("	color:yellowgreen;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	ul{\r\n");
      out.write("		list-style: none;\r\n");
      out.write("	}\r\n");
      out.write("	.logo{\r\n");
      out.write("	max-width: 1000px;\r\n");
      out.write("	height: 150px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.nav_items{\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	line-height: 40px;\r\n");
      out.write("	}\r\n");
      out.write("	.nav_items .categorymenu{\r\n");
      out.write("	width: 1024px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	justify-content: flex-start;\r\n");
      out.write("	}\r\n");
      out.write("	.nav_items .categorymenu .category{\r\n");
      out.write("	display: flex;\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	.nav_items .categorymenu .category>li{\r\n");
      out.write("		position: relative;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		align-content : center;\r\n");
      out.write("		padding: 0 15px;\r\n");
      out.write("		width: 150px;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.nav_items .categorymenu .category .sub-menu{\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	top : 40px;\r\n");
      out.write("	line-height: 40px;\r\n");
      out.write("	width : 150px;\r\n");
      out.write("	box-shadow: 0 1px 2px rgba(0,0,0,0.2);\r\n");
      out.write("	padding-left: 0;\r\n");
      out.write("	display: none;\r\n");
      out.write("	z-index: 10;\r\n");
      out.write("	background-color : rgba(255,255,255,0.5);\r\n");
      out.write("	padding-bottom: 30px;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.sub-menu>li{\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding-top: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	.sub-menu>li:hover{\r\n");
      out.write("	background-color: #ddd;\r\n");
      out.write("	}\r\n");
      out.write("	.sub-menu>li:hover a{\r\n");
      out.write("	color : black;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 21px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.category>li>a::before {\r\n");
      out.write("  content: '';\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  bottom: 0%;\r\n");
      out.write("  left: 0px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 2px;\r\n");
      out.write("  background: yellowgreen;\r\n");
      out.write("  display: block;\r\n");
      out.write("  -webkit-transform-origin: right top;\r\n");
      out.write("  -ms-transform-origin: right top;\r\n");
      out.write("  transform-origin: right top;\r\n");
      out.write("  -webkit-transform: scale(0, 1);\r\n");
      out.write("  -ms-transform: scale(0, 1);\r\n");
      out.write("  transform: scale(0, 1);\r\n");
      out.write("  -webkit-transition: transform 0.4s cubic-bezier(1, 0, 0, 1);\r\n");
      out.write("  transition: transform 0.4s cubic-bezier(1, 0, 0, 1);\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".category>li>a:hover::before {\r\n");
      out.write("  -webkit-transform-origin: left top;\r\n");
      out.write("  -ms-transform-origin: left top;\r\n");
      out.write("  transform-origin: left top;\r\n");
      out.write("  -webkit-transform: scale(1, 1);\r\n");
      out.write("  -ms-transform: scale(1, 1);\r\n");
      out.write("  transform: scale(1, 1)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#adminPage:hover{\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("	\r\n");
      out.write("/* 헤더 부분 */\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"#headmain\">\r\n");
      out.write("	<header>\r\n");
      out.write("	<!-- 좌측 상단  -->\r\n");
      out.write("		<div class=\"links\">\r\n");
      out.write("		<div class=leftlinks>\r\n");
      out.write("		");
if(loginUser==null){ 
      out.write(" \r\n");
      out.write("				<a href=\"");
      out.print(request.getContextPath() );
      out.write("/loginForm.me\" class=\"link_text\">LOGIN</a>\r\n");
      out.write("				<a href=\"");
      out.print(request.getContextPath() );
      out.write("/joinForm.me\" class=\"link_text\">JOIN</a>\r\n");
      out.write("				");
}else{
      out.write("\r\n");
      out.write("				<label for=\"\">");
      out.print( loginUser.getUserName() );
      out.write("(님)</label>\r\n");
      out.write("				<a href=\"");
      out.print(request.getContextPath() );
      out.write("/loginOutFormServlet.me\" class=\"link_text\">LOGOUT</a>\r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write("				<a href=\"#\" class=\"link_text\">MYPAGE</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("		<!-- 우측 상단 -->\r\n");
      out.write("		<div class=rightlinks>\r\n");
      out.write("				<input type=\"text\" maxlength=\"225\" tabindex=\"1\"/>\r\n");
      out.write("				<i class=\"bi bi-search\"></i>\r\n");
      out.write("				<a href=\"#\"><i class=\"bi bi-basket2-fill\"></i></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- img -->\r\n");
      out.write("		<div class=\"logo\">\r\n");
      out.write("		<a href=\"");
      out.print( request.getContextPath() );
      out.write("\" ><img src=\"");
      out.print(request.getContextPath() );
      out.write("/img/logo.png\" /></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("	<!--  nav -->\r\n");
      out.write("		<nav>\r\n");
      out.write("			<div class=\"nav_items\">\r\n");
      out.write("					<div class=\"categorymenu\">\r\n");
      out.write("					<ul class=\"category\">\r\n");
      out.write("					<li class=\"fir\">\r\n");
      out.write("						<a href=\"#\" id=\"ca\"><i class=\"bi bi-list\"></i>카테고리</a>\r\n");
      out.write("						<ul class=\"sub-menu\">\r\n");
      out.write("							<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/productList.do\">전체</a></li>\r\n");
      out.write("							<li><a href=\"#\">비건</a></li>\r\n");
      out.write("							<li><a href=\"#\">락토</a></li>\r\n");
      out.write("							<li><a href=\"#\">오보</a></li>\r\n");
      out.write("							<li><a href=\"#\">락토오보</a></li>\r\n");
      out.write("							<li><a href=\"#\">폴로</a></li>\r\n");
      out.write("							<li><a href=\"#\">페스코</a></li>\r\n");
      out.write("							<li><a href=\"#\">플렉시테리안</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("						\r\n");
      out.write("					</li>\r\n");
      out.write("					\r\n");
      out.write("						\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"#\" >신상품</a></li>\r\n");
      out.write("					<li><a href=\"#\" >베스트상품</a></li>\r\n");
      out.write("					<li><a href=\"#\" >커뮤니티</a></li>\r\n");
      out.write("					<!-- 관리자로 로그인시 나오게 하기 -->\r\n");
      out.write("					<li><form id=\"adminPage\" >상품관리</form></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("		</header>\r\n");
      out.write("		</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("	$('.fir').mouseover(function(){\r\n");
      out.write("		$(this).find('.sub-menu').stop().slideDown(500);\r\n");
      out.write("	}).mouseout(function(){\r\n");
      out.write("		$(this).find('.sub-menu').stop().slideUp(500);\r\n");
      out.write("	});\r\n");
      out.write("	$('#adminPage').click(function(){\r\n");
      out.write("		$('#adminPage').attr('action', 'ManagerProductList.pr');\r\n");
      out.write("		$('#adminPage').submit();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	</header>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("    	    \r\n");
      out.write("      \r\n");
      out.write("#visual {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  width: 960px;\r\n");
      out.write("  height: 380px;\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("  overflow: hidden;           \r\n");
      out.write("  box-shadow: 1px 5px 10px 2px #666;\r\n");
      out.write("\r\n");
      out.write("}      \r\n");
      out.write("#visual>div {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  transition: 0.3s ease;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("}\r\n");
      out.write("#visual>div.on{\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("#control { \r\n");
      out.write("  position: absolute;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  bottom: 30px;\r\n");
      out.write("  text-align: center;         \r\n");
      out.write("}\r\n");
      out.write("#control a {\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  width: 20px;\r\n");
      out.write("  height: 20px;\r\n");
      out.write("  background: #f6f5f5;                       \r\n");
      out.write("  line-height: 26px;\r\n");
      out.write("  font-size: 0.8em;\r\n");
      out.write("  border-radius: 14px;\r\n");
      out.write("  margin: 0 2px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#control a.on {\r\n");
      out.write("  background: #9ab3f5;\r\n");
      out.write("}\r\n");
      out.write("div#left>span:first-child{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  width: 50px;\r\n");
      out.write("  height: 8px;\r\n");
      out.write("  background-color: black;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  transform: translateY(63px) rotate(50deg);  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#left>span:last-child{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  width: 50px;\r\n");
      out.write("  height: 8px;\r\n");
      out.write("  background-color: black;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  transform: translateY(30px) rotate(-50deg);  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#left:hover span{\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  transition: 0.2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("div#left{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  width: 50px;\r\n");
      out.write("  height: 100px;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  left: 2.5%;\r\n");
      out.write("  transform: translate(0%, -50%);\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  transition: .4s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#right{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  width: 50px;\r\n");
      out.write("  height: 100px;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  left: 90%;\r\n");
      out.write("  transform: translate(0%, -50%);\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  transition: .4s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#right>span:first-child{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  width: 50px;\r\n");
      out.write("  height: 8px;\r\n");
      out.write("  background-color: black;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  transform: translateY(63px) rotate(-50deg);  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#right>span:last-child{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  width: 50px;\r\n");
      out.write("  height: 8px;\r\n");
      out.write("  background-color: black;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  transform: translateY(30px) rotate(50deg);  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#right:hover span{\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  transition: 0.2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"visual\">     \r\n");
      out.write("             <div class=\"on\"><a href=\"#\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/img/1.jpg\" alt=\"1\" width=\"100%\" height=\"100%\"></a></div>\r\n");
      out.write("             <div><a href=\"#\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/img/2.jpg\" alt=\"2\" width=\"100%\" height=\"100%\"></a></div>\r\n");
      out.write("             <div><a href=\"#\"><img src=\"");
      out.print( request.getContextPath() );
      out.write("/img/3.jpg\" alt=\"3\" width=\"100%\" height=\"100%\"></a></div>\r\n");
      out.write("          <section>   \r\n");
      out.write("            <div id=\"left\">\r\n");
      out.write("                <span></span>\r\n");
      out.write("                <span></span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div id=\"right\">\r\n");
      out.write("                <span></span>\r\n");
      out.write("                <span></span>\r\n");
      out.write("              </div>\r\n");
      out.write("           </section>\r\n");
      out.write("        <section id=\"control\">\r\n");
      out.write("            <a class=\"on\" href=\"#\"></a>\r\n");
      out.write("            <a href=\"#\"></a>\r\n");
      out.write("            <a href=\"#\"></a>\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("  </div>\r\n");
      out.write("		<script>\r\n");
      out.write("		var idx_lgth = $(\"#visual>div\").length;\r\n");
      out.write("		  var srt = 1;\r\n");
      out.write("		  var idx = 0;\r\n");
      out.write("		  \r\n");
      out.write("		  $(\"section>a\").click(function(){\r\n");
      out.write("		    idx = $(this).index();\r\n");
      out.write("		    srt = idx;\r\n");
      out.write("		    $(this).addClass('on').siblings().removeClass('on');\r\n");
      out.write("		    $(\"#visual>div\").eq(idx).addClass('on').siblings().removeClass('on');\r\n");
      out.write("		  });\r\n");
      out.write("		  \r\n");
      out.write("		var AutoSlide = setInterval(AutoRun, 3000);\r\n");
      out.write("\r\n");
      out.write("		function AutoRun(){\r\n");
      out.write("		  srt++;  \r\n");
      out.write("		  \r\n");
      out.write("		  if(srt == idx_lgth){\r\n");
      out.write("		      srt = 0;  \r\n");
      out.write("		  }\r\n");
      out.write("		$(\"section>a\").eq(srt).addClass('on').siblings().removeClass('on');\r\n");
      out.write("		  $(\"#visual>div\").eq(srt).addClass('on').siblings().removeClass('on');\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		$(\"#visual\").mouseover(function(){\r\n");
      out.write("		  clearInterval(AutoSlide);\r\n");
      out.write("		  $(\"#right\").css({opacity : '1'});\r\n");
      out.write("		  $(\"#left\").css({opacity : '1'});\r\n");
      out.write("		});\r\n");
      out.write("		$(\"#visual\").mouseleave(function(){\r\n");
      out.write("		   AutoSlide = setInterval(AutoRun, 3000);\r\n");
      out.write("		    $(\"#right\").css({opacity : '0'});\r\n");
      out.write("		  $(\"#left\").css({opacity : '0'});\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$(\"#right\").click(function(){\r\n");
      out.write("		  srt++;\r\n");
      out.write("		 if(srt == idx_lgth){\r\n");
      out.write("		      srt = 0;   \r\n");
      out.write("		 } \r\n");
      out.write("		 $(\"#visual>div\").eq(srt).addClass('on').siblings().removeClass('on'); $(\"section>a\").eq(srt).addClass('on').siblings().removeClass('on');\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$(\"#left\").click(function(){\r\n");
      out.write("		  srt--;\r\n");
      out.write("		  if(srt == -1){\r\n");
      out.write("		      srt = idx_lgth-1; \r\n");
      out.write("		  }\r\n");
      out.write("		 $(\"#visual>div\").eq(srt).addClass('on').siblings().removeClass('on');\r\n");
      out.write("		  $(\"section>a\").eq(srt).addClass('on').siblings().removeClass('on'); \r\n");
      out.write("		});\r\n");
      out.write("		</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("<!--  메인 페이지  -->\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("  <!-- 상단 카테고리별 네비게이터 -->\r\n");
      out.write(" <div   class=\"cateNav\" id=\"cateNavDiv\">\r\n");
      out.write("  <ul>\r\n");
      out.write("  	<li class=\"active\"><a href=\"#\">전체</a></li>\r\n");
      out.write("  	<li><a href=\"#\">비건</a></li>\r\n");
      out.write("  	<li><a href=\"#\">락토</a></li>\r\n");
      out.write("  	<li><a href=\"#\">오보</a></li>\r\n");
      out.write("  	<li><a href=\"#\">락토오보</a></li>\r\n");
      out.write("  	<li><a href=\"#\">폴로</a></li>\r\n");
      out.write("  	<li><a href=\"#\">페스코</a></li>\r\n");
      out.write("  	<li><a href=\"#\">플렉시테리안</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("	<!-- 부트스트랩 컨테이너 -->\r\n");
      out.write("\r\n");
      out.write("	<br class=\"clear\">\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"jumbotron\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=container>\r\n");
      out.write("		<div class=\"row\" align=\"center\">\r\n");
      out.write("		");
 if(pList.isEmpty() || fList.isEmpty()){ 
      out.write("\r\n");
      out.write("		<div class=\"col-md-4\">\r\n");
      out.write("			등록된 상품이 없습니다.\r\n");
      out.write("		</div>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("			");

				for(int i = 0; i < pList.size(); i++){ 
			 Product p = pList.get(i);
			 
			 
      out.write("\r\n");
      out.write("				<input type=\"hidden\" name=\"prodNo\" value=\"");
      out.print( p.getProdNo() );
      out.write("\">\r\n");
      out.write("				");
 for(int j = 0; j < fList.size(); j++){ 
      out.write("\r\n");
      out.write("				");
 Photo ph = fList.get(j); 
      out.write("\r\n");
      out.write("					");
 if(ph.getProdNo() == p.getProdNo() && ph.getType() == 0){ 
      out.write("	\r\n");
      out.write("			<div class=\"col-md-4\">\r\n");
      out.write("				<a class=\"proThumb\">\r\n");
      out.write("				\r\n");
      out.write("				<p> <img src=\"");
      out.print( request.getContextPath() );
      out.write("/thumbnail_uploadFiles/");
      out.print( ph.getImgChangeName() );
      out.write("\" width=\"200px\" height=\"200px\">\r\n");
      out.write("				<h3>");
      out.print( p.getProdName() );
      out.write("</h3>\r\n");
      out.write("				<p>");
      out.print( p.getPrice() );
      out.write("원\r\n");
      out.write("				");
      out.print( p.getProdNo() );
      out.write("\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		    			");
 } 
      out.write("\r\n");
      out.write("		    		");
 } 
      out.write("\r\n");
      out.write("				");
 } 
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		<hr>\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 페이지네이션 -->\r\n");
      out.write("	<div class=\"pagingArea\" align=\"center\">\r\n");
      out.write("			<!-- 맨 처음으로 가는 버튼 -->\r\n");
      out.write("			<!-- 이전, 이후 버튼은 활성화가 안되야함 -->\r\n");
      out.write("			<button onclick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/productList.do?currentPage=1'\">&lt;&lt;</button>\r\n");
      out.write("			<!--  이번 페이지로 가는 버튼 -->\r\n");
      out.write("			<button id=\"beforeButton\" onclick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/productList.do?currentPage=");
      out.print(pi.getCurrentPage()-1);
      out.write("'\">&lt;</button>\r\n");
      out.write("			<script>\r\n");
      out.write("			if(");
      out.print( pi.getCurrentPage() );
      out.write(" <= 1){\r\n");
      out.write("					$('#beforeButton').prop('disabled', true);\r\n");
      out.write("				}\r\n");
      out.write("			</script>\r\n");
      out.write("			\r\n");
      out.write("			<!--  숫자 버튼 -->\r\n");
      out.write("			");
 for(int i = pi.getStartPage(); i <= pi.getEndPage(); i++){ 
      out.write("\r\n");
      out.write("			");
		if(i == pi.getCurrentPage()){ 
      out.write("\r\n");
      out.write("						<button id=\"choice\" disabled>");
      out.print( i );
      out.write("</button>\r\n");
      out.write("			");
		}else{ 
      out.write("\r\n");
      out.write("						<button id=\"numButton\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/productList.do?currentPage=");
      out.print( i );
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print( i );
      out.write("</button>\r\n");
      out.write("			");
		} 
      out.write("\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("			<!--  다음 페이지로 가는 버튼 -->\r\n");
      out.write("			<button id=\"afterButton\" onclick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/productList.do?currentPage=");
      out.print(pi.getCurrentPage()+1);
      out.write("'\">&gt;</button>\r\n");
      out.write("			<script>\r\n");
      out.write("				if(");
      out.print( pi.getCurrentPage() );
      out.write(" >= ");
      out.print( pi.getMaxPage() );
      out.write("){\r\n");
      out.write("					$('#afterButton').prop('disabled', true);\r\n");
      out.write("				}			\r\n");
      out.write("			</script>\r\n");
      out.write("			<!--  맨 끝으로 가는 버튼 -->\r\n");
      out.write("			<!-- 이전, 이후 버튼은 활성화가 안되야함 -->\r\n");
      out.write("			<button onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/productList.do?currentPage=");
      out.print( pi.getMaxPage() );
      out.write("'\">&gt;&gt;</button>\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<footer>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("	.bottontitle{\r\n");
      out.write("		margin-top : 100px;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 200px;\r\n");
      out.write("		background-color: #606060;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"bottontitle\">\r\n");
      out.write("		회사소개\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write(" $('.proThumb').click(function(){\r\n");
      out.write("		console.log(123);\r\n");
      out.write("		var pNo = $(\"input[name=prodNo]\",document.form).val();\r\n");
      out.write("		console.log(pNo);\r\n");
      out.write("		location.href = \"");
      out.print( request.getContextPath() );
      out.write("/proDetail.bo?pNo=\" + pNo;\r\n");
      out.write("	}); \r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
