/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-15 02:40:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.member;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/member/../common/header.jsp", Long.valueOf(1636801378234L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("table{\r\n");
      out.write("		margin : 0 auto;\r\n");
      out.write("		width: 800px;\r\n");
      out.write("		justify-content : center;\r\n");
      out.write("		border-collapse: collapse;\r\n");
      out.write("		border-top: 1px solid #606060;\r\n");
      out.write("	}\r\n");
      out.write("	.checktd{\r\n");
      out.write("		border-bottom-width: 0px;\r\n");
      out.write("	}\r\n");
      out.write("	input[type=password]{\r\n");
      out.write("		padding-bottom: 0px;\r\n");
      out.write("		margin-bottom: 0px;\r\n");
      out.write("	}\r\n");
      out.write("	table tr td{\r\n");
      out.write("		border-bottom: 1px solid #606060;\r\n");
      out.write("		padding: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	table tr td label{\r\n");
      out.write("		font-size: 4px;\r\n");
      out.write("		padding-top: 0px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.jointitle{\r\n");
      out.write("	background: #EEEEEE;\r\n");
      out.write("	width: 230px;\r\n");
      out.write("	padding-left: 50px;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	table tr input{\r\n");
      out.write("		margin: 5px;\r\n");
      out.write("		border: 1px solid #999;\r\n");
      out.write("		padding: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	#pwdcon{\r\n");
      out.write("		font-size: 2px;\r\n");
      out.write("		display: inline;\r\n");
      out.write("		color: #999;\r\n");
      out.write("	}\r\n");
      out.write("	.phone{\r\n");
      out.write("		width: 80px;\r\n");
      out.write("	}\r\n");
      out.write("	.labeltd{\r\n");
      out.write("		padding-top: 0px;\r\n");
      out.write("		padding-left: 10px;\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	.checkbtn{\r\n");
      out.write("		margin: 30px auto;\r\n");
      out.write("		width: 600px;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		margin-bottom: 100px;\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	.checkbtn button{\r\n");
      out.write("		padding: 7px 30px;\r\n");
      out.write("		margin: 0 20px;\r\n");
      out.write("		border-style: none;\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	#deletebtn{\r\n");
      out.write("		border : 1px solid #999;\r\n");
      out.write("	}\r\n");
      out.write("	.headjoin{\r\n");
      out.write("		width: 600px;\r\n");
      out.write("		margin: 60px auto;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		font-size: 40px;\r\n");
      out.write("		margin-bottom: 20px;\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    ");

    member loginUser = (member)session.getAttribute("loginUser");
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" >\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\">\r\n");
      out.write("<style>\r\n");
      out.write("	\r\n");
      out.write("	*{\r\n");
      out.write("		box-sizing: border-box;\r\n");
      out.write("		margin: 0;\r\n");
      out.write("		padding: 0;\r\n");
      out.write("		font-family: 'poppins', snas-serif;\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	.links{\r\n");
      out.write("		max-width : 1000px;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: space-between;\r\n");
      out.write("		margin-top: 30px;\r\n");
      out.write("	}\r\n");
      out.write("	.leftlinks>a{\r\n");
      out.write("	margin-left: 20px;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	}\r\n");
      out.write("	header a{\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color:#606060;\r\n");
      out.write("	}\r\n");
      out.write("	header a:hover{\r\n");
      out.write("	color:yellowgreen;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	ul{\r\n");
      out.write("		list-style: none;\r\n");
      out.write("	}\r\n");
      out.write("	.logo{\r\n");
      out.write("	max-width: 1000px;\r\n");
      out.write("	height: 150px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.nav_items{\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	line-height: 40px;\r\n");
      out.write("	}\r\n");
      out.write("	.nav_items .categorymenu{\r\n");
      out.write("	width: 1024px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	justify-content: flex-start;\r\n");
      out.write("	}\r\n");
      out.write("	.nav_items .categorymenu .category{\r\n");
      out.write("	display: flex;\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	.nav_items .categorymenu .category>li{\r\n");
      out.write("		position: relative;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		align-content : center;\r\n");
      out.write("		padding: 0 15px;\r\n");
      out.write("		width: 150px;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.nav_items .categorymenu .category .sub-menu{\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	top : 40px;\r\n");
      out.write("	line-height: 40px;\r\n");
      out.write("	width : 150px;\r\n");
      out.write("	box-shadow: 0 1px 2px rgba(0,0,0,0.2);\r\n");
      out.write("	padding-left: 0;\r\n");
      out.write("	display: none;\r\n");
      out.write("	z-index: 10;\r\n");
      out.write("	background-color : rgba(255,255,255,0.5);\r\n");
      out.write("	padding-bottom: 30px;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.sub-menu>li{\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding-top: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	.sub-menu>li:hover{\r\n");
      out.write("	background-color: #ddd;\r\n");
      out.write("	}\r\n");
      out.write("	.sub-menu>li:hover a{\r\n");
      out.write("	color : black;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 21px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.category>li>a::before {\r\n");
      out.write("  content: '';\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  bottom: 0%;\r\n");
      out.write("  left: 0px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 2px;\r\n");
      out.write("  background: yellowgreen;\r\n");
      out.write("  display: block;\r\n");
      out.write("  -webkit-transform-origin: right top;\r\n");
      out.write("  -ms-transform-origin: right top;\r\n");
      out.write("  transform-origin: right top;\r\n");
      out.write("  -webkit-transform: scale(0, 1);\r\n");
      out.write("  -ms-transform: scale(0, 1);\r\n");
      out.write("  transform: scale(0, 1);\r\n");
      out.write("  -webkit-transition: transform 0.4s cubic-bezier(1, 0, 0, 1);\r\n");
      out.write("  transition: transform 0.4s cubic-bezier(1, 0, 0, 1);\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".category>li>a:hover::before {\r\n");
      out.write("  -webkit-transform-origin: left top;\r\n");
      out.write("  -ms-transform-origin: left top;\r\n");
      out.write("  transform-origin: left top;\r\n");
      out.write("  -webkit-transform: scale(1, 1);\r\n");
      out.write("  -ms-transform: scale(1, 1);\r\n");
      out.write("  transform: scale(1, 1)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#adminPage:hover{\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("	\r\n");
      out.write("/* 헤더 부분 */\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"#headmain\">\r\n");
      out.write("	<header>\r\n");
      out.write("	<!-- 좌측 상단  -->\r\n");
      out.write("		<div class=\"links\">\r\n");
      out.write("		<div class=leftlinks>\r\n");
      out.write("		");
if(loginUser==null){ 
      out.write(" \r\n");
      out.write("				<a href=\"");
      out.print(request.getContextPath() );
      out.write("/loginForm.me\" class=\"link_text\">LOGIN</a>\r\n");
      out.write("				<a href=\"");
      out.print(request.getContextPath() );
      out.write("/joinForm.me\" class=\"link_text\">JOIN</a>\r\n");
      out.write("				");
}else{
      out.write("\r\n");
      out.write("				<label for=\"\">");
      out.print( loginUser.getUserName() );
      out.write("(님)</label>\r\n");
      out.write("				<a href=\"");
      out.print(request.getContextPath() );
      out.write("/loginOutFormServlet.me\" class=\"link_text\">LOGOUT</a>\r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write("				<a href=\"#\" class=\"link_text\">MYPAGE</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("		<!-- 우측 상단 -->\r\n");
      out.write("		<div class=rightlinks>\r\n");
      out.write("				<input type=\"text\" maxlength=\"225\" tabindex=\"1\"/>\r\n");
      out.write("				<i class=\"bi bi-search\"></i>\r\n");
      out.write("				<a href=\"#\"><i class=\"bi bi-basket2-fill\"></i></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- img -->\r\n");
      out.write("		<div class=\"logo\">\r\n");
      out.write("		<a href=\"");
      out.print( request.getContextPath() );
      out.write("\" ><img src=\"");
      out.print(request.getContextPath() );
      out.write("/img/logo.png\" /></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("	<!--  nav -->\r\n");
      out.write("		<nav>\r\n");
      out.write("			<div class=\"nav_items\">\r\n");
      out.write("					<div class=\"categorymenu\">\r\n");
      out.write("					<ul class=\"category\">\r\n");
      out.write("					<li class=\"fir\">\r\n");
      out.write("						<a href=\"#\" id=\"ca\"><i class=\"bi bi-list\"></i>카테고리</a>\r\n");
      out.write("						<ul class=\"sub-menu\">\r\n");
      out.write("							<li><a href=\"#\">비건</a></li>\r\n");
      out.write("							<li><a href=\"#\">락토</a></li>\r\n");
      out.write("							<li><a href=\"#\">오보</a></li>\r\n");
      out.write("							<li><a href=\"#\">락토오보</a></li>\r\n");
      out.write("							<li><a href=\"#\">폴로</a></li>\r\n");
      out.write("							<li><a href=\"#\">페스코</a></li>\r\n");
      out.write("							<li><a href=\"#\">플렉시테리안</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("						\r\n");
      out.write("					</li>\r\n");
      out.write("					\r\n");
      out.write("						\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"#\" >신상품</a></li>\r\n");
      out.write("					<li><a href=\"#\" >베스트상품</a></li>\r\n");
      out.write("					<li><a href=\"#\" >커뮤니티</a></li>\r\n");
      out.write("					<li><form id=\"adminPage\" >상품관리</form></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("		</header>\r\n");
      out.write("		</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("	$('.fir').mouseover(function(){\r\n");
      out.write("		$(this).find('.sub-menu').stop().slideDown(500);\r\n");
      out.write("	}).mouseout(function(){\r\n");
      out.write("		$(this).find('.sub-menu').stop().slideUp(500);\r\n");
      out.write("	});\r\n");
      out.write("	$('#adminPage').click(function(){\r\n");
      out.write("		$('#adminPage').attr('action', 'ManagerProductList.pr');\r\n");
      out.write("		$('#adminPage').submit();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"headjoin\">회원 가입</div>\r\n");
      out.write("	<form action=\"");
      out.print( request.getContextPath() );
      out.write("/InsertJoinServlet.me\"\r\n");
      out.write("			 method=\"post\" name=\"joinForm\" onsubmit=\"return checkValue()\">\r\n");
      out.write("		<table>\r\n");
      out.write("		\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"jointitle\">아이디</td>\r\n");
      out.write("				<td ><input type=\"text\" onkeydown=\"inputIdChk()\" name = \"userid\" style=\"width: 130px;\"/>\r\n");
      out.write("				<input type=\"button\" id=\"idcheck\" value=\"중복확인\" style=\"background : yellowgreen; border-style : none; color:white;\"/>\r\n");
      out.write("				<input type=\"hidden\" name=\"idDuplication\" value=\"idUncheck\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("				\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"jointitle\">이름</td>\r\n");
      out.write("				<td><input type=\"text\" name = \"username\" style=\"width: 130px;\"/></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"jointitle\">닉네임</td>\r\n");
      out.write("				<td><input type=\"text\" onkeydown=\"inputNickChk()\" name = \"nickname\" style=\"width: 130px;\"/>\r\n");
      out.write("				<input type=\"button\" id=\"nickcheck\" value=\"중복확인\" style=\"background : yellowgreen; border-style : none; color:white;\"/>\r\n");
      out.write("				<input type=\"hidden\" name=\"nickDuplication\" value=\"nickUncheck\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("		\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td rowspan=\"2\" class=\"jointitle\">비밀번호</td>\r\n");
      out.write("				<td  class=\"checktd\"><input type=\"password\" name = \"userPwd\" id=\"userPwd\"/><div id=\"pwdcon\">영문/숫자/특수문자 조합(8-20자)</div></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"labeltd\"><label for=\"\">안전한 비밀번호 입니다.</label></td>\r\n");
      out.write("				\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td rowspan=\"2\" class=\"jointitle\">비밀번호 확인</td>\r\n");
      out.write("				<td  class=\"checktd\"><input type=\"password\" name = \"userPwdcheck\"/></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"labeltd\"><label for=\"\">비밀번호가 일치하지 않습니다.</label></td>\r\n");
      out.write("				\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"jointitle\">이메일</td>\r\n");
      out.write("				<td><input type=\"text\" style=\"width: 150px;\" id=\"email1\"name = \"email1\"/> @ \r\n");
      out.write("				<input type=\"text\" name = \"email2\" style=\"width: 150px;\" id=\"email2\"/> \r\n");
      out.write("																	<select name = \"email3\" id=\"email\">\r\n");
      out.write("																		<option value=\"1\">직접입력</option>\r\n");
      out.write("																		<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("																		<option value=\"hanmail.net\">hanmail.net</option>\r\n");
      out.write("																		<option value=\"nate.com\">nate.com</option>\r\n");
      out.write("																		<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("																		\r\n");
      out.write("																	</select>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td class=\"jointitle\">휴대폰 번호</td>\r\n");
      out.write("				<td><input type=\"tel\" class=\"phone\" name = \"phone\"style=\"width: 320px;\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<!--  \r\n");
      out.write("			<tr>\r\n");
      out.write("				<td rowspan=\"3\" class=\"jointitle\">주소</td>\r\n");
      out.write("				<td style=\"border-style: none; \"><input type=\"text\" id=\"sample4_postcode\" placeholder=\"우편번호\">\r\n");
      out.write("				<input type=\"button\" onclick=\"sample4_execDaumPostcode()\" value=\"우편번호 찾기\">\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td style=\"border-style: none;\"><input type=\"text\" id=\"sample4_roadAddress\" placeholder=\"도로명주소\" style=\" width:350px; \"></td>\r\n");
      out.write("				\r\n");
      out.write("			\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><input type=\"text\" id=\"sample4_detailAddress\" placeholder=\"상세주소\" style=\" width:350px; \"></td>\r\n");
      out.write("				\r\n");
      out.write("			</tr>\r\n");
      out.write("			-->\r\n");
      out.write("		</table>\r\n");
      out.write("		<div class=\"checkbtn\">\r\n");
      out.write("		<button type=\"submit\" name = \"joinBtn\" id=\"joinBtn\" style=\"background : #469536; color:white;\">회원가입</button>\r\n");
      out.write("		<button type=\"button\" id=\"deletebtn\"style=\"background:white; color:#606060;\" onclick=\"history.back()\">취소</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	<br>\r\n");
      out.write("	\r\n");
      out.write("	<!-- \r\n");
      out.write("	<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    //본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n");
      out.write("    function sample4_execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 도로명 주소의 노출 규칙에 따라 주소를 표시한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var roadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("                var extraRoadAddr = ''; // 참고 항목 변수\r\n");
      out.write("\r\n");
      out.write("                // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                    extraRoadAddr += data.bname;\r\n");
      out.write("                }\r\n");
      out.write("                // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                   extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('sample4_postcode').value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"sample4_roadAddress\").value = roadAddr;\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                var guideTextBox = document.getElementById(\"guide\");\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write(" -->\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	/*$('#userPwd').focusout(function(){\r\n");
      out.write("			var pw = $(this).val();\r\n");
      out.write("			 var num = pw.search(/[0-9]/g);\r\n");
      out.write("			 var eng = pw.search(/[a-z]/ig);\r\n");
      out.write("			 var spe = pw.search(/[`~!@@#$%^&*|₩₩₩'₩\";:₩/?]/gi);\r\n");
      out.write("	\r\n");
      out.write("			 if(pw.length < 8 || pw.length > 20){\r\n");
      out.write("	\r\n");
      out.write("			  alert(\"8자리 ~ 20자리 이내로 입력해주세요.\");\r\n");
      out.write("			  return false;\r\n");
      out.write("			 }else if(pw.search(/\\s/) != -1){\r\n");
      out.write("			  alert(\"비밀번호는 공백 없이 입력해주세요.\");\r\n");
      out.write("			  return false;\r\n");
      out.write("			 }else if(num < 0 || eng < 0 || spe < 0 ){\r\n");
      out.write("			  alert(\"영문,숫자, 특수문자를 혼합하여 입력해주세요.\");\r\n");
      out.write("			  return false;\r\n");
      out.write("			 }else {\r\n");
      out.write("				console.log(\"통과\"); \r\n");
      out.write("			    return true;\r\n");
      out.write("			 }\r\n");
      out.write("		})*/\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	$('#email').change(function(){ \r\n");
      out.write("		$(\"#email option:selected\").each(function () { \r\n");
      out.write("			if($(this).val()== '1'){ \r\n");
      out.write("				$(\"#email2\").val(''); \r\n");
      out.write("				$(\"#email2\").attr(\"disabled\",false);\r\n");
      out.write("			}else{\r\n");
      out.write("				$(\"#email2\").val($(this).text());\r\n");
      out.write("				$(\"#email2\").attr(\"disabled\",true); \r\n");
      out.write("			} \r\n");
      out.write("			\r\n");
      out.write("			}); \r\n");
      out.write("		\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("	document.getElementById('idcheck').onclick = function(){\r\n");
      out.write("		window.open('checkIdForm.me','idCheckForm',\r\n");
      out.write("				'width=600, height=200,resizable = no, scrollbars = no');\r\n");
      out.write("	}\r\n");
      out.write("	document.getElementById('nickcheck').onclick = function(){\r\n");
      out.write("		window.open('checkNickForm.me','nickCheckForm',\r\n");
      out.write("				'width=600, height=200,resizable = no, scrollbars = no');\r\n");
      out.write("	}\r\n");
      out.write("	function checkValue(){\r\n");
      out.write("    \r\n");
      out.write("        var form = document.joinForm;\r\n");
      out.write("    \r\n");
      out.write("        if(!form.userid.value){\r\n");
      out.write("            alert(\"아이디를 입력하세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        if(form.idDuplication.value != \"idCheck\"){\r\n");
      out.write("            alert(\"아이디 중복체크를 해주세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("        if(!form.username.value){\r\n");
      out.write("            alert(\"이름을 입력하세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        if(!form.nickname.value){\r\n");
      out.write("            alert(\"닉네임을 입력하세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        if(form.nickDuplication.value != \"nickCheck\"){\r\n");
      out.write("            alert(\"닉네임 중복체크를 해주세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        if(!form.userPwd.value){\r\n");
      out.write("            alert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // 비밀번호와 비밀번호 확인에 입력된 값이 동일한지 확인\r\n");
      out.write("        if(form.userPwd.value != form.userPwdcheck.value ){\r\n");
      out.write("            alert(\"비밀번호를 동일하게 입력하세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }    \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        if(!form.email1.value || !form.email2.value ||form.email3.value==\"1\" ){\r\n");
      out.write("            alert(\"메일 주소를 입력하세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("        if(!form.phone.value){\r\n");
      out.write("            alert(\"전화번호를 입력하세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        if(isNaN(form.phone.value)){\r\n");
      out.write("            alert(\"전화번호는 - 제외한 숫자만 입력해주세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("    }\r\n");
      out.write("	function inputIdChk(){\r\n");
      out.write("        document.joinForm.idDuplication.value =\"idUncheck\";\r\n");
      out.write("    }\r\n");
      out.write("	\r\n");
      out.write("	function inputNickChk(){\r\n");
      out.write("        document.joinForm.nickDuplication.value =\"nickUncheck\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
